spring:
  application:
    name: zmrpc-demo-consumer
server:
  port: 9980

zmrpc:
  providers: http://127.0.0.1:8081/,http://127.0.0.1:8082/,http://127.0.0.1:8083/
  zkServer: 127.0.0.1:2181
  zkRoot: zmrpc

app:
  id: app1
  namespace: public
  env: dev
  retries: 2
  timeout: 1000

logging:
  level:
    root: error
    me.zhongmingmao.zmrpc: debug
