### 获取用户信息
POST http://localhost:8080
Content-Type: application/json

{
  "service": "me.zhongmingmao.zmrpc.demo.api.UserService",
  "method": "findById",
  "args": [
    100
  ]
}

### mock
POST http://localhost:8080
Content-Type: application/json

{
  "service": "me.zhongmingmao.zmrpc.demo.api.UserService",
  "method": "toString",
  "args": []
}

### 获取订单信息
POST http://localhost:8080
Content-Type: application/json

{
  "service": "me.zhongmingmao.zmrpc.demo.api.OrderService",
  "method": "findById",
  "args": [
    200
  ]
}