### 获取用户信息 1
POST http://localhost:9980/?id=101
Content-Type: application/json

{
  "service": "me.zhongmingmao.zmrpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [
    100
  ]
}

### 获取用户信息 2
POST http://localhost:8081
Content-Type: application/json

{
  "service": "me.zhongmingmao.zmrpc.demo.api.UserService",
  "methodSign": "findById@2_int_java.lang.String",
  "args": [
    200,
    "BB"
  ]
}

### mock
POST http://localhost:8081
Content-Type: application/json

{
  "service": "me.zhongmingmao.zmrpc.demo.api.UserService",
  "methodSign": "toString",
  "args": []
}

### 获取订单信息
POST http://localhost:8081
Content-Type: application/json

{
  "service": "me.zhongmingmao.zmrpc.demo.api.OrderService",
  "methodSign": "findById@1_java.lang.Integer",
  "args": [
    201
  ]
}